set number relativenumber
let mapleader = ','
set clipboard+=unnamedplus

" Copy relative path (src/foo.txt)
nnoremap <leader>cp :let @+=expand("%")<CR>

" Copy absolute path (/something/src/foo.txt)
nnoremap <leader>cP :let @+=expand("%:p")<CR>

" Copy filename (foo.txt)
nnoremap <leader>ct :let @+=expand("%:t")<CR>

" Copy directory name (/something/src)
nnoremap <leader>cph :let @+=expand("%:p:h")<CR>
